### ISSUE TITLE
intermediate-data is empty

### ISSUE THREAD

**Issue by stusmall** [jswest/russian-troll-tweets-exploration#1]
The readme mentioned english-only-doc2vec-data.json should be in there.  Where can I find this data?

**Comment by jswest** [comment]
@stusmall Sorry, I should be clearer in the README. You'll need to generate that file by running through the [Jupyter notebook](https://github.com/jswest/russian-troll-tweets-exploration/blob/master/model-topics.ipynb) before you can spool up the JS visualization. Let me know if you have any trouble with that!

**Comment by stusmall** [comment]
Ah! I skipped ahead in the instructions.  Thank you.
